export const FETCH_DELIVERY = "FETCH_DELIVERY";
export const FETCH_DELIVERY_PENDING = "FETCH_DELIVERY_PENDING";
export const FETCH_DELIVERY_REJECTED = "FETCH_DELIVERY_REJECTED";
export const FETCH_DELIVERY_FULFILLED = "FETCH_DELIVERY_FULFILLED";